[dev]
  framework = "vite"
  command = "vite"
  targetPort = 5173
  port = 8888
  functions = "netlify/functions"
  publish = "dist"

[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
