[dev]
  framework = "vite"
  command = "vite"
  targetPort = 5173
  port = 8888
  functions = "netlify/functions"
  publish = "dist"

[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

# هندل کردن ریدایرکت درخواست‌های API به سرورلس
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# هندل کردن مسیرهای React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
